//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;

using LinqToDB;
using LinqToDB.Mapping;

using Pilot.DataCore.Infrastructure;

namespace Pilot.DataCore
{
	/// <summary>
	/// Database       : Pilot
	/// Data Source    : KLG-W005
	/// Server Version : 11.00.3128
	/// </summary>
	public partial class DataManager : LinqToDB.Data.DataConnection
	{
		public ITable<User> User { get { return this.GetTable<User>(); } }

		partial void InitDataContext();
	}

	[Table(Schema="dbo", Name="User")]
	public partial class User : IEntity
	{
		[PrimaryKey, NotNull    ] public Guid      Id       { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string    Name     { get; set; } // nvarchar(100)
		[Column,     NotNull    ] public DateTime  Created  { get; set; } // datetime
		[Column,     NotNull    ] public DateTime  Modified { get; set; } // datetime
		[Column,        Nullable] public DateTime? Deleted  { get; set; } // datetime
	}
}
